version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - teamavail-network

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    command: npm start
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=password 
    networks:
      - teamavail-network

networks:
  teamavail-network:
    driver: bridge

volumes:
  redis_data:
    driver: local