version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - teamavail-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - teamavail-network

networks:
  teamavail-network:
    driver: bridge

volumes:
  redis_data:
    driver: local